name: shauntig_yard
description: Application implementing the shaunting yard algorithm to parse infix math expressions
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  stack: ^0.0.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
