
const String CLOSING_BRACKET = ')';
const String OPENING_BRACKET = '(';
const String PLUS_SIGN = '+';
const String MINUS_SIGN = '-';
const String DIVISION_SIGN = '/';
const String MULTIPLICATION_SIGN = '*';
const List<String> SUPPORTED_OPERATORS =[PLUS_SIGN, MINUS_SIGN, MULTIPLICATION_SIGN, DIVISION_SIGN, OPENING_BRACKET, CLOSING_BRACKET];